name: First Action

on: [push]

jobs:
    build:
      runs-on: aquasec/trivy-scan@v2

      steps:
          - name: Checkout code
            uses: actions/checkout@v3

          - name: Trivy Scan
            uses: aquasec/trivy-scan@latest

          - name: Trivy Start Scan
            run: trivy fs .
